// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Post_Office;

namespace Post_Office.Migrations
{
    [DbContext(typeof(PostOfficeContext))]
    partial class PostOfficeContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:Collation", "Cyrillic_General_CI_AS")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.11")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Post_Office.Client", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(6)
                        .HasColumnType("nchar(6)")
                        .IsFixedLength(true);

                    b.Property<bool>("Bonus")
                        .HasColumnType("bit");

                    b.Property<string>("Email")
                        .HasMaxLength(25)
                        .HasColumnType("nchar(25)")
                        .HasColumnName("email")
                        .IsFixedLength(true);

                    b.Property<int>("ParcelId")
                        .HasColumnType("int")
                        .HasColumnName("parcel_id");

                    b.Property<int>("PhoneNumber")
                        .HasColumnType("int")
                        .HasColumnName("Phone_number");

                    b.HasKey("Id");

                    b.ToTable("Client");
                });

            modelBuilder.Entity("Post_Office.Parcel", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<string>("AdressId")
                        .IsRequired()
                        .HasMaxLength(5)
                        .HasColumnType("nchar(5)")
                        .HasColumnName("adress_id")
                        .IsFixedLength(true);

                    b.Property<double>("Height")
                        .HasColumnType("float")
                        .HasColumnName("height");

                    b.Property<double>("Weight")
                        .HasColumnType("float")
                        .HasColumnName("weight");

                    b.HasKey("Id");

                    b.ToTable("parcel");
                });

            modelBuilder.Entity("Post_Office.Person", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<string>("ClientId")
                        .IsRequired()
                        .HasMaxLength(6)
                        .HasColumnType("nchar(6)")
                        .HasColumnName("Client_Id")
                        .IsFixedLength(true);

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(25)
                        .HasColumnType("nchar(25)")
                        .HasColumnName("First_name")
                        .IsFixedLength(true);

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(25)
                        .HasColumnType("nchar(25)")
                        .HasColumnName("Last_name")
                        .IsFixedLength(true);

                    b.HasKey("Id");

                    b.ToTable("Person");
                });

            modelBuilder.Entity("Post_Office.PostOffice", b =>
                {
                    b.Property<string>("AdressId")
                        .HasMaxLength(5)
                        .HasColumnType("nchar(5)")
                        .HasColumnName("adress_id")
                        .IsFixedLength(true);

                    b.Property<int>("PostOffice1")
                        .HasColumnType("int")
                        .HasColumnName("post_office");

                    b.HasKey("AdressId");

                    b.ToTable("Post_office");
                });
#pragma warning restore 612, 618
        }
    }
}
